DROP SCHEMA IF EXISTS ESTRELA_BET;
CREATE SCHEMA ESTRELA_BET;

CREATE TABLE ESTRELA_BET.Company (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CNPJ TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE ESTRELA_BET.Employees (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CPF TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  company_id INTEGER NOT NULL,
  FOREIGN KEY (company_id) REFERENCES ESTRELA_BET.Company (id)
);